FROM python:3.8-slim-buster

# Select workdir
WORKDIR /usr/src/osm-detective

# Copy requirements generated by poetry
COPY ./requirements.txt ./requirements.txt

# Install dependency
RUN pip install -r requirements.txt

# Copy Source code
COPY . .

# Run scheduled
CMD [ "python3", "./main.py" ]
