en = {
    "changeset_count": "User has {v} changesets",
    "new_account": "User's account had been made {v} days ago",
    "user_block": "User has been blocked {v} times before",
    "big_area": "Change are is too large",
    "no_editor": "Editor has not been specified",
    "uncommon_editor": "User used {v} as editor",
    "no_comment": "Changeset has no comment",
    "sus_word_comment": "Changeset's comment contains suspicious words",
    "no_source": "No source has been specified for changeset",
    "sus_word_source": "Changeset's source contains suspicious words",
    "review_requested": "User has requested review",
    "exceed_del_percen": "{v}%% of changeset is deletion",
    "mass_deletaion": "Mass deletation: {v}",
    "entity_mass_deletion": "Mass entity deletation: {v}",
    "mass_modification": "Mass modification: {v}",
    "mass_creation": "Mass creation: {v}",
    "building_mass_creation": "Mass building creation: {v}",
    "important_id": "Changeset contains important id: {v}",
    "important_name": "Changeset contains important name: {v}",
    "important_tag": "Changeset contains important tag: {v}",
    "versioned_entity": "User changed entity with version {v}",
    # Warnings
    "almost_junction": "Almost junction:{n}={v}",
    "close_nodes": "Very close points:{n}={v}",
    "crossing_ways": "Crossing ways:{n}={v}",
    "disconnected_way": "Disconnected way:{n}={v}",
    "impossible_oneway": "Impossible oneway:{n}={v}",
    "incompatible_source": "Incompatible source:{n}={v}",
    "mismatched_geometry": "Mismatched geometry:{n}={v}",
    "missing_role": "Missing role:{n}={v}",
    "missing_tag": "Missing tag:{n}={v}",
    "outdated_tags": "Outdated tags:{n}={v}",
    "private_data": "Private information:{n}={v}",
    "suspicious_name": "Generic name={v}",
    "unsquare_way": "Unsquare corners:{n}={v}"
}

fa = {
    "changeset_count": "کاربر فقط {v} بستهٔ تغییر دارد",
    "new_account": "حساب کاربر {v} روز پیش ساخته شده",
    "user_block": "کاربر {v} بار قبلا مسدود شده",
    "big_area": "محوطه تغییر بسیار بزرگ است",
    "no_editor": "ادیتور مشخص نشده",
    "uncommon_editor": "ادیتور مشخص شده {v} است",
    "no_comment": "بستهٔ تغییرات دارای توضیحات نیست",
    "sus_word_comment": "توضیحات دارای کلمات مشکوک است",
    "no_source": "منبع مشخص نشده",
    "sus_word_source": "منبع دارای کلمات مشکوک است",
    "review_requested": "کاربر درخواست بررسی دارد",
    "exceed_del_percen": "{v}%% درصد تغییرات حذف است",
    "mass_deletaion": "حذف انبوه: {v}",
    "entity_mass_deletion": "حذف انبوه غیر جزئی: {v}",
    "mass_modification": "اصلاح انبوه: {v}",
    "mass_creation": "اضافه کردن انبوه: {v}",
    "building_mass_creation": "اضافه کردن انبوه ساختمان: {v}",
    "important_id": "دارای عارضه مهم: {v}",
    "important_name": "دارای نام مهم: {v}",
    "important_tag": "دارای تگ مهم: {v}",
    "versioned_entity": "کاربر عارضه با ورژن {v} تغییر داده",
    # Warnings
    "almost_junction": "تقاطع‌مانند:{n}={v}",
    "close_nodes": "نقاط خیلی به هم نزدیک:{n}={v}",
    "crossing_ways": "خطوط از روی هم رد شده:{n}={v}",
    "disconnected_way": "خطوط از هم جدا شده:{n}={v}",
    "impossible_oneway": "یک‌طرفه غیرممکن:{n}={v}",
    "incompatible_source": "منبع نامشخص:{n}={v}",
    "mismatched_geometry": "نوع عارضه نادرست:{n}={v}",
    "missing_role": "ریلیشن اشتباه:{n}={v}",
    "missing_tag": "بدون تگ:{n}={v}",
    "outdated_tags": "تگ منقضی شده:{n}={v}",
    "private_data": "اطلاعات شخصی:{n}={v}",
    "suspicious_name": "اسامی عمومی={v}",
    "unsquare_way": "گوشه‌ی نامربعی:{n}={v}"
}

langs = {"en": en,
         "fa": fa}