de = {
    "changeset_count": "Nutzer hat {v} Änderungssätze",
    "new_account": "Nutzerkonto wurde vor {v} Tagen erstellt",
    "user_block": "Nutzer wurde bereits {v} Mal blockiert",
    "big_area": "Das Hochladegebiet dieses Änderungssatzes ist sehr groß",
    "no_editor": "Editor wurde nicht angegeben",
    "uncommon_editor": "Nutzer hat {v} als Editor verwendet",
    "no_comment": "Änderungssatz ohne Kommentar",
    "sus_word_comment": "Verdächtige Wörter im Kommentar des Änderungssatzes",
    "no_source": "Keine Quelle für den Änderungssatz angegeben",
    "sus_word_source": "Verdächtige Wörter in der Quellenangabe des Änderungssatzes",
    "review_requested": "Nutzer hat um Überprüfung der Bearbeitungen gebeten",
    "exceed_del_percen": "{v} des Änderungssatzes sind gelöschte Objekte",
    "mass_deletaion": "Sehr viele gelöschte Objekte: {v}",
    "entity_mass_deletion": "Sehr viele gelöschte Entitäten: {v}",
    "mass_modification": "Sehr viele bearbeitete Objekte: {v}",
    "mass_creation": "Sehr viele neu erstellte Objekte: {v}",
    "building_mass_creation": "Sehr viele gelöschte Gebäude: {v}",
    "important_id": "Änderungssatz enthält wichtige id: {v}",
    "important_name": "Änderungssatz enthält wichtigen Namen: {v}",
    "important_tag": "Änderungssatz enthält wichtige Tags: {v}",
    "versioned_entity": "Nutzer hat Entität mit Version {v} geändert",
    # Warnings
    "almost_junction": "Fast-Kreuzung:{n}={v}",
    "close_nodes": "Sehr nahe beieinander liegende Knoten:{n}={v}",
    "crossing_ways": "Überschneidende Wege:{n}={v}",
    "disconnected_way": "Unverbundene Wege:{n}={v}",
    "impossible_oneway": "Unmögliche Einbahnstraße:{n}={v}",
    "incompatible_source": "Nicht kompatible Quelle:{n}={v}",
    "mismatched_geometry": "Nicht zusammen passende Geometrie:{n}={v}",
    "missing_role": "Fehlende Rolle:{n}={v}",
    "missing_tag": "Fehlender Tag:{n}={v}",
    "outdated_tags": "Veraltete Tags:{n}={v}",
    "private_data": "Private Informationen:{n}={v}",
    "suspicious_name": "Generischer Name={v}",
    "unsquare_way": "Ecke mit beinahe rechtem Winkel:{n}={v}"
}

en = {
    "changeset_count": "User has {v} changesets",
    "new_account": "User's account had been made {v} days ago",
    "user_block": "User has been blocked {v} times before",
    "big_area": "Bounding box of this changeset is very large",
    "no_editor": "Editor has not been specified",
    "uncommon_editor": "User used {v} as editor",
    "no_comment": "Changeset has no comment",
    "sus_word_comment": "Changeset's comment contains suspicious words",
    "no_source": "No source has been specified for changeset",
    "sus_word_source": "Changeset's source contains suspicious words",
    "review_requested": "User has requested review",
    "exceed_del_percen": "{v} percent of changeset is deletion",
    "mass_deletaion": "Mass deletion: {v}",
    "entity_mass_deletion": "Mass entity deletion: {v}",
    "mass_modification": "Mass modification: {v}",
    "mass_creation": "Mass creation: {v}",
    "building_mass_creation": "Mass building creation: {v}",
    "important_id": "Changeset contains important id: {v}",
    "important_name": "Changeset contains important name: {v}",
    "important_tag": "Changeset contains important tag: {v}",
    "versioned_entity": "User changed entity with version {v}",
    # Warnings
    "almost_junction": "Almost junction:{n}={v}",
    "close_nodes": "Very close points:{n}={v}",
    "crossing_ways": "Crossing ways:{n}={v}",
    "disconnected_way": "Disconnected way:{n}={v}",
    "impossible_oneway": "Impossible oneway:{n}={v}",
    "incompatible_source": "Incompatible source:{n}={v}",
    "mismatched_geometry": "Mismatched geometry:{n}={v}",
    "missing_role": "Missing role:{n}={v}",
    "missing_tag": "Missing tag:{n}={v}",
    "outdated_tags": "Outdated tags:{n}={v}",
    "private_data": "Private information:{n}={v}",
    "suspicious_name": "Generic name={v}",
    "unsquare_way": "Unsquare corners:{n}={v}"
}

fa = {
    "changeset_count": "کاربر فقط {v} بستهٔ تغییر دارد",
    "new_account": "حساب کاربر {v} روز پیش ساخته شده",
    "user_block": "کاربر {v} بار قبلا مسدود شده",
    "big_area": "محوطه تغییر بسیار بزرگ است",
    "no_editor": "ادیتور مشخص نشده",
    "uncommon_editor": "ادیتور مشخص شده {v} است",
    "no_comment": "بستهٔ تغییرات دارای توضیحات نیست",
    "sus_word_comment": "توضیحات دارای کلمات مشکوک است",
    "no_source": "منبع مشخص نشده",
    "sus_word_source": "منبع دارای کلمات مشکوک است",
    "review_requested": "کاربر درخواست بررسی دارد",
    "exceed_del_percen": "{v} درصد تغییرات حذف است",
    "mass_deletaion": "حذف انبوه: {v}",
    "entity_mass_deletion": "حذف انبوه غیر جزئی: {v}",
    "mass_modification": "اصلاح انبوه: {v}",
    "mass_creation": "اضافه کردن انبوه: {v}",
    "building_mass_creation": "اضافه کردن انبوه ساختمان: {v}",
    "important_id": "دارای عارضه مهم: {v}",
    "important_name": "دارای نام مهم: {v}",
    "important_tag": "دارای تگ مهم: {v}",
    "versioned_entity": "کاربر عارضه با ورژن {v} تغییر داده",
    # Warnings
    "almost_junction": "تقاطع‌مانند:{n}={v}",
    "close_nodes": "نقاط خیلی به هم نزدیک:{n}={v}",
    "crossing_ways": "خطوط از روی هم رد شده:{n}={v}",
    "disconnected_way": "خطوط از هم جدا شده:{n}={v}",
    "impossible_oneway": "یک‌طرفه غیرممکن:{n}={v}",
    "incompatible_source": "منبع نامشخص:{n}={v}",
    "mismatched_geometry": "نوع عارضه نادرست:{n}={v}",
    "missing_role": "ریلیشن اشتباه:{n}={v}",
    "missing_tag": "بدون تگ:{n}={v}",
    "outdated_tags": "تگ منقضی شده:{n}={v}",
    "private_data": "اطلاعات شخصی:{n}={v}",
    "suspicious_name": "اسامی عمومی={v}",
    "unsquare_way": "گوشه‌ی نامربعی:{n}={v}"
}

langs = {"de": de,
         "en": en,
         "fa": fa}