translation = {
    "Review requested": u"درخواست بررسی دارد",
    "suspect_word": u"دارای کلمات مشکوک",
    "Unknown iD instance": u"نوع iD مشخص نشده‌است",
    "Software editor was not declared": u"نرم‌افزار ادیتور مشخص نشده‌است",
    "possible import": u"احتمال ایمپورت",
    "mass modification": u"تغییرات انبوه",
    "mass deletion": u"حذف انبوه",
    "Almost junction": u"اتصال تقریبی",
    "Very close points": u"نقاط نزدیک به هم",
    "Crossing ways": u"خطوط روی هم رد شده",
    "Disconnected way": u"خطوط منفصل",
    "Impossible oneway": u"یکطرفه غیرممکن",
    "Mismatched geometry": u"هندسه اشتباه",
    "Missing role": u"ریلیشن role ندارد",
    "Missing tag": u"تگ ندارد",
    "Outdated tags": u"تگ منقضی‌شده",
    "Private information": u"اطلاعات شخصی وارد شده",
    "Generic name": u"اسامی عمومی انتخاب شده",
    "Unsquare corners": u"گوشه غیر مربعی",
    "User has multiple blocks": u"این کاربر چندین بار قبلا مسدود‌ شده‌است",
    "New mapper": u"کاربر جدید",
    "Not reported": u"گزارش نشده‌است"
}