{
 "title": "OSM-Detective",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "per_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Total Changes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Creates",
   "type": "graph",
   "description": "All creates",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_create_total{type=\"all\"}[$per_interval])"
    }
   ]
  },
  {
   "title": "All Modifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_modify_total{type=\"all\"}[$per_interval])"
    }
   ]
  },
  {
   "title": "All Deletes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_deletes_total{type=\"all\"}[$per_interval])"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Changesets in day",
   "type": "stat",
   "description": "Number of changesets in a day",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "increase(changesets_total[1d])" }
   ]
  },
  {
   "title": "Changesets per Cycle",
   "type": "graph",
   "description": "Total Changesets Per Cycles",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "changeset_per_cycle" }
   ]
  },
  {
   "title": "Cycles",
   "type": "stat",
   "description": "Fetch cycles count",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(fetch_cycles_total[$per_interval])"
    }
   ]
  },
  { "title": "API calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cumulative API calls",
   "type": "graph",
   "description": "Total API calls",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "api_requests_total" }
   ]
  },
  {
   "title": "Average API response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "api_request_seconds_sum / api_request_seconds_count"
    }
   ]
  },
  { "title": "Change Types", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Creates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_create_total{type=~\"node|way|relation\"}[$per_interval])"
    }
   ]
  },
  {
   "title": "Modification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_modify_total{type=~\"node|way|relation\"}[$per_interval])"
    }
   ]
  },
  {
   "title": "Deletion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_deletes_total{type=~\"node|way|relation\"}[$per_interval])"
    }
   ]
  },
  { "title": "Ref Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Ref Node Creates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_create_total{type=\"ref_node\"}[$per_interval])"
    }
   ]
  },
  {
   "title": "Ref Node Modifications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_modify_total{type=\"ref_node\"}[$per_interval])"
    }
   ]
  },
  {
   "title": "Ref Node Deletions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_deletes_total{type=\"ref_node\"}[$per_interval])"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Creates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_create_total{type=~\"highway|building\"}[$per_interval])"
    }
   ]
  },
  {
   "title": "Modification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_modify_total{type=~\"highway|building\"}[$per_interval])"
    }
   ]
  },
  {
   "title": "Deletion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(change_deletes_total{type=~\"highway|building\"}[$per_interval])"
    }
   ]
  }
 ]
}