global:
  scrape_interval:     3m
  evaluation_interval: 3m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'osm_detective'
    scrape_interval: 2m
    static_configs:
      - targets: ['osm-detective:8000']
